[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "awox"
version = "0.2.0"
description = "AWOX API control"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "requests>=2.31",
    "PyYAML>=6.0",
    "paho-mqtt>=2.0",
]

[project.urls]
Homepage = "https://forge.piair.dev/Piair/awox-smart-control"

[project.scripts]
awox = "awox.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["awox*"]