[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "awox"
version = "0.4.0"
description = "Control AwoX smart wifi devices"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.31",
    "PyYAML>=6.0",
    "paho-mqtt>=2.0",
    "cryptography>= 42.0.0",
    "python-dotenv>= 1.2.4",
    "platformdirs>=3",
]
authors = [
    { name = "Pierre Tellier", email = "awox@piair.dev" },
]
license = "MIT"

[project.urls]
Homepage = "https://github.com/Pierre-TELLIER/awox-connect-wifi"

[project.scripts]
awox = "awox.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["awox*"]
