# This endpoint is derived from the Android application. It should be the same for everyone.
mqtt:
  endpoint: "a3n0qz5q2o66io.iot.us-east-1.amazonaws.com"
  port: 443


storage:
  state_file: "./state.yaml"
  certificate_directory: "../certs"

logging:
  level: "INFO"
